variable "do_token" {}
variable "do_ssh_key_name" {}
variable "geoip_account" {}
variable "geoip_license" {}
variable "ssh_pub_key" {}
variable "ssh_pvt_key" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "my_email" {}
variable "my_ip" {}
variable "aws_region" {}
