- become: yes
  hosts: all
  name: email-app-install
  tasks:
    - name: upload email app
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../app/send_email.js"
        dest: /home/ec2-user
        owner: ec2-user
        group: ec2-user
        mode: 0644
